### PR TITLE
Fixed clicking operators twice (Fixes #7)

### LINKED ISSUE #7: Error when clicking multiple times the same operator
When I do 8 / / 2 the result is 0.

*Expected result*: 4

*Todo:*

* Create a test for this case
* Fix the issue after you have the failing test
* as always in a new branch

### PR DESCRIPTION
**Pull request by BorislavkoDumic**

### CODE REVIEW

**Comment by BorislavkoDumic** [comment]
This will fix #7

File: src/containers/CalculatorContainers.js [hunk 1]
```diff
@@ -51,6 +51,7 @@ export class CalculatorContainers extends Component {
 }
 
 const mapStateToProps = state => {
+    console.log(state)
```
Comment (attrib) [inline src/containers/CalculatorContainers.js]: console log should not be here

File: src/__tests__/reducers/reducers.test.js [hunk 2]
```diff
@@ -60,12 +60,14 @@ describe("When action is clicked", () => {
     const state = {
       displayValue: "0",
       operator: operators.PLUS,
-      previusNumber: 0
+      previusNumber: 0,
+      lastButton:null
```
Comment (attrib) [inline src/__tests__/reducers/reducers.test.js]: indention is wrong. There should be a space after the colon. (multiple times)

File: src/reducers/calculator.js [hunk 3]
```diff
@@ -21,28 +22,36 @@ export const calculate = (displayValue, previusNumber, operator) => {
...
         ...state,
+        lastButton: action.number,
         displayValue:
           state.displayValue === "0"
             ? action.number.toString()
             : `${state.displayValue}${action.number}`
       };
     case actionTypes.INPUT_OPERATOR:
-      return {
+      let a = {
```
Comment (attrib) [inline src/reducers/calculator.js]: `a` is a very bad variable name. Pick something more describing for it.

File: src/reducers/calculator.js [hunk 4]
```diff
@@ -21,28 +22,36 @@ export const calculate = (displayValue, previusNumber, operator) => {
...
+        ...state,
         displayValue: "0",
-        operator: action.operator,
-        previusNumber: state.operator
+        operator: action.operator
+      };
+      let lastButton = a.lastButton;
+      if (lastButton !== a.operator) {
```
Comment (attrib) [inline src/reducers/calculator.js]: As you directly accessing `lastButton` and do not need `lastButton` somewhere else, you could just directly use `a.lastButton` instead of first assign it to a new variable.

File: cypress/integration/calculator_app.complex.js [hunk 5]
```diff
@@ -51,3 +51,18 @@ describe("Complex calculator operations", () => {
...
+  });
+  it("Get error after calcualtion (8//2) from #7", () => {
+    cy.get("[data-cy=button8]").click();
+    cy.get("[data-cy=buttonDivide").click();
+    cy.get("[data-cy=buttonDivide").click();
+    cy.get("[data-cy=button2]").click();
+    cy.get("[data-cy=buttonEqual]").click();
+    cy.get("[data-cy=displayResult]").contains("4");
+    cy.get("[data-cy=buttonClear]").click();
+  });
```
Comment (attrib) [inline cypress/integration/calculator_app.complex.js:67]: Add an additional test here for `8*/2=4` (switching operator)

**Review by attrib — CHANGES_REQUESTED** [review]

File: src/reducers/calculator.js [hunk 6]
```diff
@@ -21,28 +22,38 @@ export const calculate = (displayValue, previusNumber, operator) => {
...
-        previusNumber: state.operator
-          ? calculate(
-              parseFloat(state.displayValue),
-              state.previusNumber,
-              state.operator
-            )
-          : parseFloat(state.displayValue)
+        operator: action.operator
       };
+      if (state.operator && parseFloat(state.displayValue) !== 0) {
```
Comment (attrib) [inline src/reducers/calculator.js]: extract `parseFloat` to variable

**Review by attrib — CHANGES_REQUESTED** [review]

File: src/reducers/calculator.js (hunk 6 above)
Comment (BorislavkoDumic) [reply src/reducers/calculator.js]: Fixed.

**Review by attrib — APPROVED** [review]
